spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop?allowPublicKeyRetrieval=true&useSSL=false&useTimezone=true&serverTimezone=GMT-3&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  thymeleaf:
    cache: false
  server:
    error:
      whitelabel:
        enabled: false
    servlet:
      session:
        cookie:
          http-only: true
        tracking-modes:
          - cookie
